project:
    type: website
    render:
        - src/notebooks_list.qmd
        - src/notebooks/Python Examples/*.ipynb
        # - src/notebooks/R Examples/*.ipynb

execute:
    freeze: auto

website:
    title: MGnify Notebooks
    favicon: src/static-resources/mgnify_logo.png
    page-navigation: true

    body-header: |
        :::{.callout-note}
        ## This is a static preview
        You can run and edit these examples interactively on [Galaxy](https://usegalaxy.eu/root?tool_id=interactive_tool_mgnify_notebook)
        :::

    repo-url: https://github.com/ebi-metagenomics/notebooks
    repo-subdir: src
    repo-actions: [edit, issue]

    navbar:
        right:
            - href: https://usegalaxy.eu/root?tool_id=interactive_tool_mgnify_notebook
              text: Run on Galaxy

    sidebar:
        style: docked
        search: true

        contents:
            - href: src/notebooks_list.qmd

        tools:
            - icon: github
              menu:
                  - text: Notebooks source
                    url: https://github.com/ebi-metagenomics/notebooks
                  - text: MGnify repositories
                    url: https://github.com/ebi-metagenomics
            - icon: question-circle-fill
              text: Help
              href: mailto:metagenomics-help@ebi.ac.uk
format:
    html:
        theme:
            - cosmo
            - src/static-resources/styles.scss
        toc: true