project:
    type: website
    render:
        - src/docs.qmd
        - src/docs/*.md
        - src/notebooks_list.qmd
        - src/notebooks/Python Examples/*.ipynb
        # - src/notebooks/R Examples/*.ipynb

execute:
    freeze: auto

ipynb-filters:
    - src/templates/notebook-static-preview.py

website:
    title: MGnify Resources
    favicon: src/static-resources/mgnify_logo.png
    page-navigation: true

    repo-url: https://github.com/ebi-metagenomics/notebooks
    repo-subdir: src
    repo-actions: [edit, issue]

    navbar:
        right:
            - href: https://www.ebi.ac.uk/metagenomics
              text: Open MGnify
            - href: https://usegalaxy.eu/root?tool_id=interactive_tool_mgnify_notebook
              text: Run notebooks on Galaxy
            - href: https://status.mgnify.org
              text: Service status

    sidebar:
        style: docked
        search: true

        contents:
            - section: "Documentation"
              href: src/docs.qmd
              contents: src/docs/*
            - href: src/notebooks_list.qmd

        tools:
            - icon: github
              menu:
                  - text: Notebooks source
                    url: https://github.com/ebi-metagenomics/notebooks
                  - text: MGnify repositories
                    url: https://github.com/ebi-metagenomics
            - icon: question-circle-fill
              text: Help
              href: mailto:metagenomics-help@ebi.ac.uk
format:
    html:
        theme:
            - cosmo
            - src/static-resources/styles.scss
        toc: true