project:
    type: website
    render:
        - src/docs.qmd
        - src/docs/*.md
        - src/docs/*.qmd
        - src/notebooks_list.qmd
        - src/notebooks/Python Examples/*.ipynb
        - src/notebooks/R Examples/*.ipynb

execute:
    freeze: auto

ipynb-filters:
    - src/templates/notebook-static-preview.py

website:
    title: MGnify Resources
    site-url: https://docs.mgnify.org
    favicon: src/static-resources/mgnify_logo.png
    page-navigation: true

    repo-url: https://github.com/ebi-metagenomics/notebooks
    repo-actions: [edit, issue]

    navbar:
        right:
            - href: https://www.ebi.ac.uk/metagenomics
              text: Open MGnify
            - href: https://usegalaxy.eu/root?tool_id=interactive_tool_mgnify_notebook
              text: Run notebooks on Galaxy
            - href: https://status.mgnify.org
              text: Service status

    sidebar:
        style: docked
        search: true

        contents:
            - href: src/docs/about.md
            - section: "Data flow"
              contents:
              - src/docs/dataflow.md
              - src/docs/multiomics_submission.md
            - section: "Analyses"
              contents:
              - src/docs/analysis.md
              - src/docs/additional-analyses.md
            - section: "Website & API"
              contents:
              - src/docs/portal.md
              - src/docs/api.md
            - href: src/docs/mgnify-genomes.md
            - section: "MGnify Proteins"
              href: src/docs/mgnify-proteins.md
              contents:
                - src/docs/mgnify-proteins-web.md
                - src/docs/mgnify-proteins-sequence-search.md
                - src/docs/mgnify-proteins-big-query.qmd
            - href: src/docs/faqs.md
            - href: src/docs/glossary.md
            - href: src/notebooks_list.qmd

        tools:
            - icon: github
              menu:
                  - text: Notebooks source
                    url: https://github.com/ebi-metagenomics/notebooks
                  - text: MGnify repositories
                    url: https://github.com/ebi-metagenomics
            - icon: question-circle-fill
              text: Help
              href: mailto:metagenomics-help@ebi.ac.uk
format:
    html:
        theme:
            - cosmo
            - src/static-resources/styles.scss
        toc: true
        code-overflow: wrap