version: '3'

tasks:
  add-py-notebook:
    summary: |
      Creates a new Python-language notebook stub from a template.

      Set the TITLE and AUTHOR variables, which are used to name
      the notebook file and set them in the notebook front matter.

      Usage: TITLE='Notebook Name' AUTHOR='Your Name' task add-py-notebook
    cmds:
      - cp src/templates/python.ipynb "src/notebooks/Python Examples/{{.TITLE}}.ipynb"
      - sed -i '' 's/::NBTITLE::/{{.TITLE}}/g' "src/notebooks/Python Examples/{{.TITLE}}.ipynb"
      - sed -i '' 's/::NBAUTHOR::/{{.AUTHOR}}/g' "src/notebooks/Python Examples/{{.TITLE}}.ipynb"
    preconditions:
      - sh: test -n "{{.TITLE}}"
        msg: "TITLE parameter missing. Set: TITLE='Notebook Name' AUTHOR='Your Name' task add-py-notebook"
      - sh: test -n "{{.AUTHOR}}"
        msg: "AUTHOR parameter missing. Set: TITLE='Notebook Name' AUTHOR='Your Name' task add-py-notebook"

  edit-notebooks:
    summary: |
      Opens Jupyter Lab (via Docker) in edit mode – with the notebooks source bound to this repository

      The files in src/notebooks are mounted as editable, and served on port 8888.
    cmds:
      - docker run -it -v $PWD/src/notebooks:/home/jovyan/mgnify-examples -p 8888:8888 quay.io/microbiome-informatics/emg-notebooks.dev:latest

  build-static-docker:
    summary: |
      Builds a docker image with Quarto included, for statically rendering the notebook outputs.

      The built image is tagged as `notebooks-static`.
    cmds:
      - docker build -f docker/docs.Dockerfile -t notebooks-static .
    status:
      - docker image inspect notebooks-static

  render-static:
    summary: |
      Runs and renders the notebooks as a static website

      The site is built to ./_site
    cmds:
      - docker run -it -v $PWD:/opt/repo -w /opt/repo notebooks-static render --execute
    deps: [build-static-docker]

  preview-static:
    summary: |
      Runs, renders, and serveces the notebooks as a static website, watching for changes
    cmds:
      - echo 'When the rendering is finished, the static preview of notebooks will be at http://127.0.0.1:4444 ...'
      - docker run -it -v $PWD:/opt/repo -w /opt/repo -p 4444:4444 notebooks-static preview --no-browser --port 4444 --host 0.0.0.0
    deps: [build-static-docker]