# Extra dependencies, installed by Conda, in addition to those from the docker image 
# https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-datascience-notebook
channels:
  - conda-forge
dependencies:
  - bioconda::bioconductor-phyloseq=1.38.0
  - bioconda::bioconductor-metagenomeSeq=1.36.0
  - bioconda::bioconductor-microbiomeMarker=1.0.0
  - bioconda::bioconductor-siamcat=1.14.0
  - bioconda::muscle=5.1
  - pip
  - pip:
    - jsonapi-client
    - py3Dmol==1.8.1
    - biopython==1.79
    - mg-toolkit==0.10.1
    - rich-msa==0.1.0
  - r-vegan=2.5_7
