# Extra dependencies, installed by Conda, in addition to those from the docker image 
# https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-datascience-notebook
channels:
  - conda-forge
dependencies:
  - bioconda::bioconductor-phyloseq=1.38.0
  - bioconda::bioconductor-siamcat
  - pip
  - pip:
    - jsonapi-client
  - r-vegan=2.5_7
