# https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-datascience-notebook
channels:
  - conda-forge
dependencies:
  - bioconda::bioconductor-phyloseq=1.42.0
  - bioconda::bioconductor-metagenomeSeq=1.40.0
  - bioconda::bioconductor-microbiomeMarker=1.4.0
  - bioconda::bioconductor-siamcat=2.2.0
  - conda-forge::r-reshape2=1.4.4
  - conda-forge::r-vegan=2.6_4
  - pip
  - pip:
    - jsonapi-client==0.9.9
