name: mgnify-py-env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python==3.11
  - pyspark==3.3.2
  - openjdk
  - jsonapi-client==0.9.9
  - pandas==2.1.0
  - ipykernel==6.25.1
  - matplotlib==3.7.2
  - seaborn==0.12.2
  - plotly==5.16.1
  - biopython==1.81
  - pyarrow==13.0.0
  - leafmap==0.26.0
  - geopandas==0.14.0
  - pip
  - pip:
    - sourmash==4.1.2
