# https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#jupyter-datascience-notebook
name: mgnify-r-env
channels:
  - conda-forge
dependencies:
  - bioconda::bioconductor-phyloseq=1.42.0
  - bioconda::bioconductor-metagenomeSeq=1.40.0
  - bioconda::bioconductor-microbiomeMarker=1.4.0
  - bioconda::bioconductor-siamcat=2.2.0
  - bioconda::bioconductor-pathview=1.38.0
  - bioconda::bioconductor-aldex2=1.30.0
  - bioconda::bioconductor-keggrest=1.38.0
  - conda-forge::r-reshape2=1.4.4
  - conda-forge::r-vegan=2.6_4
  - conda-forge::r-devtools=2.4.5
  - conda-forge::r-irkernel=1.3.2
  - conda-forge::r-tidyverse=2.0.0
  - conda-forge::r-ggplot2=3.4.1
  - conda-forge::r-dplyr=1.1.2
  - conda-forge::r-tidyjson=0.3.2
  - conda-forge::r-data.table=1.14.8
  
