name: mgnify-r-env
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bioconductor-phyloseq=1.42.0
  - bioconductor-metagenomeSeq=1.40.0
  - bioconductor-microbiomeMarker=1.4.0
  - bioconductor-siamcat=2.2.0
  - r-reshape2=1.4.4
  - r-vegan=2.6_4
  - r-devtools=2.4.5
  - r-irkernel=1.3.2
  - r-tidyverse=2.0.0
  - r-ggplot2=3.4.1
  - bioconductor-pathview=1.38.0
  - bioconductor-aldex2=1.30.0
  - bioconductor-keggrest=1.38.0
  - r-dplyr=1.1.2
  - r-tidyjson=0.3.2
  - r-data.table=1.15.4
