name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Free up disk space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: true
        swap-storage: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Dockerfile
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./docker/Dockerfile
        load: true
        push: false
        tags: quay.io/microbiome-informatics/emg-notebooks.dev:latest

    - name: Login to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Push
      run: |
        docker tag quay.io/microbiome-informatics/emg-notebooks.dev:latest quay.io/microbiome-informatics/emg-notebooks.dev:${{ github.ref_name }}
        docker push quay.io/microbiome-informatics/emg-notebooks.dev:${{ github.ref_name }}
