name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Free up disk space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: true
        swap-storage: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Login to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Build and push Python Docker image
      uses: docker/build-push-action@v7
      with:
        context: .
        file: ./images/python/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          quay.io/microbiome-informatics/emg-notebooks-python.dev:latest
          quay.io/microbiome-informatics/emg-notebooks-python.dev:${{ github.ref_name }}

    - name: Build and push R Docker image
      uses: docker/build-push-action@v7
      with:
        context: .
        file: ./images/r/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          quay.io/microbiome-informatics/emg-notebooks-r.dev:latest
          quay.io/microbiome-informatics/emg-notebooks-r.dev:${{ github.ref_name }}
