name: Test

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Free up disk space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: true
        swap-storage: false

    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Download Shiny Proxy
      run: wget -O shiny-proxy/shinyproxy-2.6.1.jar https://www.shinyproxy.io/downloads/shinyproxy-2.6.1.jar

    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install test suite dependencies
      working-directory: ./tests
      run: npm install

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Dockerfile
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./docker/Dockerfile
        load: true
        tags: quay.io/microbiome-informatics/emg-notebooks.dev:latest
        pushImage: false

    - name: Run tests
      working-directory: ./tests
      run: npm test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: launching-jupyter-lab-screenshot
        path: |
          tests/launching_jl.png
          tests/shiny_proxy_launched.png
          tests/jl_launched.png

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: quay.io/microbiome-informatics/emg-notebooks.dev:latest
        tags: latest, ${{ vars.GITHUB_REF_NAME }}
        registry: quay.io/microbiome-informatics
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"