name: Test

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Download Shiny Proxy
      run: wget -O shiny-proxy/shinyproxy-2.6.0.jar https://www.shinyproxy.io/downloads/shinyproxy-2.6.0.jar

    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install test suite dependencies
      working-directory: ./tests
      run: npm install

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Dockerfile
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./shiny-proxy/test.Dockerfile
        load: true
        tags: quay.io/microbiome-informatics/emg-notebooks.dev

    - name: Run tests
      working-directory: ./tests
      run: npm test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: launching-jupyter-lab-screenshot
        path: |
          tests/launching_jl.png
          tests/shiny_proxy_launched.png